name: platform_ui
description: A Flutter library which renders native looking widgets on different platforms

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.12.0
